//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IsNullable=false)]
public partial class FictionBook {
    
    private FictionBookStylesheet[] stylesheetField;
    
    private FictionBookDescription descriptionField;
    
    private bodyType bodyField;
    
    private FictionBookBinary[] binaryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stylesheet")]
    public FictionBookStylesheet[] stylesheet {
        get {
            return this.stylesheetField;
        }
        set {
            this.stylesheetField = value;
        }
    }
    
    /// <remarks/>
    public FictionBookDescription description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public bodyType body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("binary")]
    public FictionBookBinary[] binary {
        get {
            return this.binaryField;
        }
        set {
            this.binaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class FictionBookStylesheet {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class dateType {
    
    private System.DateTime valueField;
    
    private bool valueFieldSpecified;
    
    private string langField;
    
    private string valueField1;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueSpecified {
        get {
            return this.valueFieldSpecified;
        }
        set {
            this.valueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField1;
        }
        set {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class outPutDocumentType {
    
    private partShareInstructionType[] partField;
    
    private string nameField;
    
    private docGenerationInstructionType createField;
    
    private bool createFieldSpecified;
    
    private float priceField;
    
    private bool priceFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("part")]
    public partShareInstructionType[] part {
        get {
            return this.partField;
        }
        set {
            this.partField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public docGenerationInstructionType create {
        get {
            return this.createField;
        }
        set {
            this.createField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createSpecified {
        get {
            return this.createFieldSpecified;
        }
        set {
            this.createFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceSpecified {
        get {
            return this.priceFieldSpecified;
        }
        set {
            this.priceFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class partShareInstructionType {
    
    private string typeField;
    
    private string hrefField;
    
    private docGenerationInstructionType includeField;
    
    public partShareInstructionType() {
        this.typeField = "simple";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public docGenerationInstructionType include {
        get {
            return this.includeField;
        }
        set {
            this.includeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public enum docGenerationInstructionType {
    
    /// <remarks/>
    require,
    
    /// <remarks/>
    allow,
    
    /// <remarks/>
    deny,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class shareInstructionType {
    
    private object[] itemsField;
    
    private shareModesType modeField;
    
    private docGenerationInstructionType includeallField;
    
    private float priceField;
    
    private bool priceFieldSpecified;
    
    private string currencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("output-document-class", typeof(outPutDocumentType))]
    [System.Xml.Serialization.XmlElementAttribute("part", typeof(partShareInstructionType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public shareModesType mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("include-all")]
    public docGenerationInstructionType includeall {
        get {
            return this.includeallField;
        }
        set {
            this.includeallField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceSpecified {
        get {
            return this.priceFieldSpecified;
        }
        set {
            this.priceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public enum shareModesType {
    
    /// <remarks/>
    free,
    
    /// <remarks/>
    paid,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class sequenceType {
    
    private sequenceType[] sequenceField;
    
    private string nameField;
    
    private string numberField;
    
    private string langField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sequence")]
    public sequenceType[] sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class sectionType {
    
    private titleType titleField;
    
    private epigraphType[] epigraphField;
    
    private imageType imageField;
    
    private annotationType annotationField;
    
    private object[] itemsField;
    
    private ItemsChoiceType7[] itemsElementNameField;
    
    private string idField;
    
    private string langField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public titleType title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("epigraph", Order=1)]
    public epigraphType[] epigraph {
        get {
            return this.epigraphField;
        }
        set {
            this.epigraphField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public imageType image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public annotationType annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cite", typeof(citeType), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("empty-line", typeof(object), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(imageType), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(pType), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("poem", typeof(poemType), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("section", typeof(sectionType), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("subtitle", typeof(pType), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("table", typeof(tableType), Order=4)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=5)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType7[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class titleType {
    
    private object[] itemsField;
    
    private string langField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("empty-line", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(pType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class pType : styleType {
    
    private string idField;
    
    private string styleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string style {
        get {
            return this.styleField;
        }
        set {
            this.styleField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(tdType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(pType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class styleType {
    
    private object[] itemsField;
    
    private ItemsChoiceType4[] itemsElementNameField;
    
    private string[] textField;
    
    private string langField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("a", typeof(linkType))]
    [System.Xml.Serialization.XmlElementAttribute("code", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("emphasis", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(inlineImageType))]
    [System.Xml.Serialization.XmlElementAttribute("strikethrough", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("style", typeof(namedStyleType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(styleType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType4[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class linkType {
    
    private object[] itemsField;
    
    private ItemsChoiceType2[] itemsElementNameField;
    
    private string[] textField;
    
    private string typeField;
    
    private string hrefField;
    
    private string type1Field;
    
    public linkType() {
        this.typeField = "simple";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("code", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("emphasis", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(inlineImageType))]
    [System.Xml.Serialization.XmlElementAttribute("strikethrough", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("style", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType2[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("type", DataType="token")]
    public string type1 {
        get {
            return this.type1Field;
        }
        set {
            this.type1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class styleLinkType {
    
    private object[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("code", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("emphasis", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(inlineImageType))]
    [System.Xml.Serialization.XmlElementAttribute("strikethrough", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("style", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(styleLinkType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class inlineImageType {
    
    private string typeField;
    
    private string hrefField;
    
    private string altField;
    
    public inlineImageType() {
        this.typeField = "simple";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alt {
        get {
            return this.altField;
        }
        set {
            this.altField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    code,
    
    /// <remarks/>
    emphasis,
    
    /// <remarks/>
    image,
    
    /// <remarks/>
    strikethrough,
    
    /// <remarks/>
    strong,
    
    /// <remarks/>
    style,
    
    /// <remarks/>
    sub,
    
    /// <remarks/>
    sup,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IncludeInSchema=false)]
public enum ItemsChoiceType2 {
    
    /// <remarks/>
    code,
    
    /// <remarks/>
    emphasis,
    
    /// <remarks/>
    image,
    
    /// <remarks/>
    strikethrough,
    
    /// <remarks/>
    strong,
    
    /// <remarks/>
    style,
    
    /// <remarks/>
    sub,
    
    /// <remarks/>
    sup,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class namedStyleType {
    
    private object[] itemsField;
    
    private ItemsChoiceType3[] itemsElementNameField;
    
    private string[] textField;
    
    private string langField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("a", typeof(linkType))]
    [System.Xml.Serialization.XmlElementAttribute("code", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("emphasis", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(inlineImageType))]
    [System.Xml.Serialization.XmlElementAttribute("strikethrough", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("style", typeof(namedStyleType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(styleType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(styleType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType3[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IncludeInSchema=false)]
public enum ItemsChoiceType3 {
    
    /// <remarks/>
    a,
    
    /// <remarks/>
    code,
    
    /// <remarks/>
    emphasis,
    
    /// <remarks/>
    image,
    
    /// <remarks/>
    strikethrough,
    
    /// <remarks/>
    strong,
    
    /// <remarks/>
    style,
    
    /// <remarks/>
    sub,
    
    /// <remarks/>
    sup,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IncludeInSchema=false)]
public enum ItemsChoiceType4 {
    
    /// <remarks/>
    a,
    
    /// <remarks/>
    code,
    
    /// <remarks/>
    emphasis,
    
    /// <remarks/>
    image,
    
    /// <remarks/>
    strikethrough,
    
    /// <remarks/>
    strong,
    
    /// <remarks/>
    style,
    
    /// <remarks/>
    sub,
    
    /// <remarks/>
    sup,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class tdType : styleType {
    
    private string idField;
    
    private string styleField;
    
    private string colspanField;
    
    private string rowspanField;
    
    private alignType alignField;
    
    private vAlignType valignField;
    
    public tdType() {
        this.alignField = alignType.left;
        this.valignField = vAlignType.top;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string style {
        get {
            return this.styleField;
        }
        set {
            this.styleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string colspan {
        get {
            return this.colspanField;
        }
        set {
            this.colspanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string rowspan {
        get {
            return this.rowspanField;
        }
        set {
            this.rowspanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(alignType.left)]
    public alignType align {
        get {
            return this.alignField;
        }
        set {
            this.alignField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(vAlignType.top)]
    public vAlignType valign {
        get {
            return this.valignField;
        }
        set {
            this.valignField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public enum alignType {
    
    /// <remarks/>
    left,
    
    /// <remarks/>
    right,
    
    /// <remarks/>
    center,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public enum vAlignType {
    
    /// <remarks/>
    top,
    
    /// <remarks/>
    middle,
    
    /// <remarks/>
    bottom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class epigraphType {
    
    private object[] itemsField;
    
    private pType[] textauthorField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cite", typeof(citeType))]
    [System.Xml.Serialization.XmlElementAttribute("empty-line", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(pType))]
    [System.Xml.Serialization.XmlElementAttribute("poem", typeof(poemType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text-author")]
    public pType[] textauthor {
        get {
            return this.textauthorField;
        }
        set {
            this.textauthorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class citeType {
    
    private object[] itemsField;
    
    private ItemsChoiceType6[] itemsElementNameField;
    
    private pType[] textauthorField;
    
    private string idField;
    
    private string langField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("empty-line", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(pType))]
    [System.Xml.Serialization.XmlElementAttribute("poem", typeof(poemType))]
    [System.Xml.Serialization.XmlElementAttribute("subtitle", typeof(pType))]
    [System.Xml.Serialization.XmlElementAttribute("table", typeof(tableType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType6[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text-author")]
    public pType[] textauthor {
        get {
            return this.textauthorField;
        }
        set {
            this.textauthorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class poemType {
    
    private titleType titleField;
    
    private epigraphType[] epigraphField;
    
    private object[] itemsField;
    
    private pType[] textauthorField;
    
    private dateType dateField;
    
    private string idField;
    
    private string langField;
    
    /// <remarks/>
    public titleType title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("epigraph")]
    public epigraphType[] epigraph {
        get {
            return this.epigraphField;
        }
        set {
            this.epigraphField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stanza", typeof(poemTypeStanza))]
    [System.Xml.Serialization.XmlElementAttribute("subtitle", typeof(pType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text-author")]
    public pType[] textauthor {
        get {
            return this.textauthorField;
        }
        set {
            this.textauthorField = value;
        }
    }
    
    /// <remarks/>
    public dateType date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class poemTypeStanza {
    
    private titleType titleField;
    
    private pType subtitleField;
    
    private pType[] vField;
    
    private string langField;
    
    /// <remarks/>
    public titleType title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public pType subtitle {
        get {
            return this.subtitleField;
        }
        set {
            this.subtitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("v")]
    public pType[] v {
        get {
            return this.vField;
        }
        set {
            this.vField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class tableType {
    
    private tableTypeTR[] trField;
    
    private string styleField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tr")]
    public tableTypeTR[] tr {
        get {
            return this.trField;
        }
        set {
            this.trField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string style {
        get {
            return this.styleField;
        }
        set {
            this.styleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class tableTypeTR {
    
    private tdType[] itemsField;
    
    private ItemsChoiceType5[] itemsElementNameField;
    
    private alignType alignField;
    
    public tableTypeTR() {
        this.alignField = alignType.left;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("td", typeof(tdType))]
    [System.Xml.Serialization.XmlElementAttribute("th", typeof(tdType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public tdType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType5[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(alignType.left)]
    public alignType align {
        get {
            return this.alignField;
        }
        set {
            this.alignField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IncludeInSchema=false)]
public enum ItemsChoiceType5 {
    
    /// <remarks/>
    td,
    
    /// <remarks/>
    th,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IncludeInSchema=false)]
public enum ItemsChoiceType6 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("empty-line")]
    emptyline,
    
    /// <remarks/>
    p,
    
    /// <remarks/>
    poem,
    
    /// <remarks/>
    subtitle,
    
    /// <remarks/>
    table,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class imageType {
    
    private string typeField;
    
    private string hrefField;
    
    private string altField;
    
    private string titleField;
    
    private string idField;
    
    public imageType() {
        this.typeField = "simple";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alt {
        get {
            return this.altField;
        }
        set {
            this.altField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class annotationType {
    
    private object[] itemsField;
    
    private ItemsChoiceType8[] itemsElementNameField;
    
    private string idField;
    
    private string langField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cite", typeof(citeType))]
    [System.Xml.Serialization.XmlElementAttribute("empty-line", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(pType))]
    [System.Xml.Serialization.XmlElementAttribute("poem", typeof(poemType))]
    [System.Xml.Serialization.XmlElementAttribute("subtitle", typeof(pType))]
    [System.Xml.Serialization.XmlElementAttribute("table", typeof(tableType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType8[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IncludeInSchema=false)]
public enum ItemsChoiceType8 {
    
    /// <remarks/>
    cite,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("empty-line")]
    emptyline,
    
    /// <remarks/>
    p,
    
    /// <remarks/>
    poem,
    
    /// <remarks/>
    subtitle,
    
    /// <remarks/>
    table,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IncludeInSchema=false)]
public enum ItemsChoiceType7 {
    
    /// <remarks/>
    cite,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("empty-line")]
    emptyline,
    
    /// <remarks/>
    image,
    
    /// <remarks/>
    p,
    
    /// <remarks/>
    poem,
    
    /// <remarks/>
    section,
    
    /// <remarks/>
    subtitle,
    
    /// <remarks/>
    table,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(notesBodyType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class bodyType {
    
    private imageType imageField;
    
    private titleType titleField;
    
    private epigraphType[] epigraphField;
    
    private sectionType[] sectionField;
    
    private string langField;
    
    /// <remarks/>
    public imageType image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    public titleType title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("epigraph")]
    public epigraphType[] epigraph {
        get {
            return this.epigraphField;
        }
        set {
            this.epigraphField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("section")]
    public sectionType[] section {
        get {
            return this.sectionField;
        }
        set {
            this.sectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class notesBodyType : bodyType {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class textFieldType {
    
    private string langField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class authorType {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("email", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("first-name", typeof(textFieldType))]
    [System.Xml.Serialization.XmlElementAttribute("home-page", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("id", typeof(string), DataType="token")]
    [System.Xml.Serialization.XmlElementAttribute("last-name", typeof(textFieldType))]
    [System.Xml.Serialization.XmlElementAttribute("middle-name", typeof(textFieldType))]
    [System.Xml.Serialization.XmlElementAttribute("nickname", typeof(textFieldType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    email,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("first-name")]
    firstname,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("home-page")]
    homepage,
    
    /// <remarks/>
    id,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("last-name")]
    lastname,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("middle-name")]
    middlename,
    
    /// <remarks/>
    nickname,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="title-infoType", Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class titleinfoType {
    
    private titleinfoTypeGenre[] genreField;
    
    private titleinfoTypeAuthor[] authorField;
    
    private textFieldType booktitleField;
    
    private annotationType annotationField;
    
    private textFieldType keywordsField;
    
    private dateType dateField;
    
    private inlineImageType[] coverpageField;
    
    private string langField;
    
    private string srclangField;
    
    private authorType[] translatorField;
    
    private sequenceType[] sequenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("genre")]
    public titleinfoTypeGenre[] genre {
        get {
            return this.genreField;
        }
        set {
            this.genreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("author")]
    public titleinfoTypeAuthor[] author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("book-title")]
    public textFieldType booktitle {
        get {
            return this.booktitleField;
        }
        set {
            this.booktitleField = value;
        }
    }
    
    /// <remarks/>
    public annotationType annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <remarks/>
    public textFieldType keywords {
        get {
            return this.keywordsField;
        }
        set {
            this.keywordsField = value;
        }
    }
    
    /// <remarks/>
    public dateType date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("image", IsNullable=false)]
    public inlineImageType[] coverpage {
        get {
            return this.coverpageField;
        }
        set {
            this.coverpageField = value;
        }
    }
    
    /// <remarks/>
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("src-lang")]
    public string srclang {
        get {
            return this.srclangField;
        }
        set {
            this.srclangField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("translator")]
    public authorType[] translator {
        get {
            return this.translatorField;
        }
        set {
            this.translatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sequence")]
    public sequenceType[] sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class titleinfoTypeGenre {
    
    private string matchField;
    
    private string valueField;
    
    public titleinfoTypeGenre() {
        this.matchField = "100";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("100")]
    public string match {
        get {
            return this.matchField;
        }
        set {
            this.matchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0/genres")]
//public enum genreType {

//    /// <remarks/>
//    accounting,

//    /// <remarks/>
//    adv_animal,

//    /// <remarks/>
//    adv_geo,

//    /// <remarks/>
//    adv_history,

//    /// <remarks/>
//    adv_maritime,

//    /// <remarks/>
//    adv_western,

//    /// <remarks/>
//    adventure,

//    /// <remarks/>
//    antique,

//    /// <remarks/>
//    antique_ant,

//    /// <remarks/>
//    antique_east,

//    /// <remarks/>
//    antique_european,

//    /// <remarks/>
//    antique_myths,

//    /// <remarks/>
//    antique_russian,

//    /// <remarks/>
//    aphorism_quote,

//    /// <remarks/>
//    architecture_book,

//    /// <remarks/>
//    auto_regulations,

//    /// <remarks/>
//    banking,

//    /// <remarks/>
//    beginning_authors,

//    /// <remarks/>
//    child_adv,

//    /// <remarks/>
//    child_det,

//    /// <remarks/>
//    child_education,

//    /// <remarks/>
//    child_prose,

//    /// <remarks/>
//    child_sf,

//    /// <remarks/>
//    child_tale,

//    /// <remarks/>
//    child_verse,

//    /// <remarks/>
//    children,

//    /// <remarks/>
//    cinema_theatre,

//    /// <remarks/>
//    city_fantasy,

//    /// <remarks/>
//    comp_db,

//    /// <remarks/>
//    comp_hard,

//    /// <remarks/>
//    comp_osnet,

//    /// <remarks/>
//    comp_programming,

//    /// <remarks/>
//    comp_soft,

//    /// <remarks/>
//    comp_www,

//    /// <remarks/>
//    computers,

//    /// <remarks/>
//    design,

//    /// <remarks/>
//    det_action,

//    /// <remarks/>
//    det_classic,

//    /// <remarks/>
//    det_crime,

//    /// <remarks/>
//    det_espionage,

//    /// <remarks/>
//    det_hard,

//    /// <remarks/>
//    det_history,

//    /// <remarks/>
//    det_irony,

//    /// <remarks/>
//    det_police,

//    /// <remarks/>
//    det_political,

//    /// <remarks/>
//    detective,

//    /// <remarks/>
//    dragon_fantasy,

//    /// <remarks/>
//    dramaturgy,

//    /// <remarks/>
//    economics,

//    /// <remarks/>
//    essays,

//    /// <remarks/>
//    fantasy_fight,

//    /// <remarks/>
//    foreign_action,

//    /// <remarks/>
//    foreign_adventure,

//    /// <remarks/>
//    foreign_antique,

//    /// <remarks/>
//    foreign_business,

//    /// <remarks/>
//    foreign_children,

//    /// <remarks/>
//    foreign_comp,

//    /// <remarks/>
//    foreign_contemporary,

//    /// <remarks/>
//    foreign_contemporary_lit,

//    /// <remarks/>
//    foreign_desc,

//    /// <remarks/>
//    foreign_detective,

//    /// <remarks/>
//    foreign_dramaturgy,

//    /// <remarks/>
//    foreign_edu,

//    /// <remarks/>
//    foreign_fantasy,

//    /// <remarks/>
//    foreign_home,

//    /// <remarks/>
//    foreign_humor,

//    /// <remarks/>
//    foreign_language,

//    /// <remarks/>
//    foreign_love,

//    /// <remarks/>
//    foreign_novel,

//    /// <remarks/>
//    foreign_other,

//    /// <remarks/>
//    foreign_poetry,

//    /// <remarks/>
//    foreign_prose,

//    /// <remarks/>
//    foreign_psychology,

//    /// <remarks/>
//    foreign_publicism,

//    /// <remarks/>
//    foreign_religion,

//    /// <remarks/>
//    foreign_sf,

//    /// <remarks/>
//    geo_guides,

//    /// <remarks/>
//    geography_book,

//    /// <remarks/>
//    global_economy,

//    /// <remarks/>
//    historical_fantasy,

//    /// <remarks/>
//    home,

//    /// <remarks/>
//    home_cooking,

//    /// <remarks/>
//    home_crafts,

//    /// <remarks/>
//    home_diy,

//    /// <remarks/>
//    home_entertain,

//    /// <remarks/>
//    home_garden,

//    /// <remarks/>
//    home_health,

//    /// <remarks/>
//    home_pets,

//    /// <remarks/>
//    home_sex,

//    /// <remarks/>
//    home_sport,

//    /// <remarks/>
//    humor,

//    /// <remarks/>
//    humor_anecdote,

//    /// <remarks/>
//    humor_fantasy,

//    /// <remarks/>
//    humor_prose,

//    /// <remarks/>
//    humor_verse,

//    /// <remarks/>
//    industries,

//    /// <remarks/>
//    job_hunting,

//    /// <remarks/>
//    literature_18,

//    /// <remarks/>
//    literature_19,

//    /// <remarks/>
//    literature_20,

//    /// <remarks/>
//    love_contemporary,

//    /// <remarks/>
//    love_detective,

//    /// <remarks/>
//    love_erotica,

//    /// <remarks/>
//    love_fantasy,

//    /// <remarks/>
//    love_history,

//    /// <remarks/>
//    love_sf,

//    /// <remarks/>
//    love_short,

//    /// <remarks/>
//    magician_book,

//    /// <remarks/>
//    management,

//    /// <remarks/>
//    marketing,

//    /// <remarks/>
//    military_special,

//    /// <remarks/>
//    music_dancing,

//    /// <remarks/>
//    narrative,

//    /// <remarks/>
//    newspapers,

//    /// <remarks/>
//    nonf_biography,

//    /// <remarks/>
//    nonf_criticism,

//    /// <remarks/>
//    nonf_publicism,

//    /// <remarks/>
//    nonfiction,

//    /// <remarks/>
//    org_behavior,

//    /// <remarks/>
//    paper_work,

//    /// <remarks/>
//    pedagogy_book,

//    /// <remarks/>
//    periodic,

//    /// <remarks/>
//    personal_finance,

//    /// <remarks/>
//    poetry,

//    /// <remarks/>
//    popadanec,

//    /// <remarks/>
//    popular_business,

//    /// <remarks/>
//    prose_classic,

//    /// <remarks/>
//    prose_counter,

//    /// <remarks/>
//    prose_history,

//    /// <remarks/>
//    prose_military,

//    /// <remarks/>
//    prose_rus_classic,

//    /// <remarks/>
//    prose_su_classics,

//    /// <remarks/>
//    psy_alassic,

//    /// <remarks/>
//    psy_childs,

//    /// <remarks/>
//    psy_generic,

//    /// <remarks/>
//    psy_personal,

//    /// <remarks/>
//    psy_sex_and_family,

//    /// <remarks/>
//    psy_social,

//    /// <remarks/>
//    psy_theraphy,

//    /// <remarks/>
//    real_estate,

//    /// <remarks/>
//    ref_dict,

//    /// <remarks/>
//    ref_encyc,

//    /// <remarks/>
//    ref_guide,

//    /// <remarks/>
//    ref_ref,

//    /// <remarks/>
//    reference,

//    /// <remarks/>
//    religion,

//    /// <remarks/>
//    religion_esoterics,

//    /// <remarks/>
//    religion_rel,

//    /// <remarks/>
//    religion_self,

//    /// <remarks/>
//    russian_contemporary,

//    /// <remarks/>
//    russian_fantasy,

//    /// <remarks/>
//    sci_biology,

//    /// <remarks/>
//    sci_chem,

//    /// <remarks/>
//    sci_culture,

//    /// <remarks/>
//    sci_history,

//    /// <remarks/>
//    sci_juris,

//    /// <remarks/>
//    sci_linguistic,

//    /// <remarks/>
//    sci_math,

//    /// <remarks/>
//    sci_medicine,

//    /// <remarks/>
//    sci_philosophy,

//    /// <remarks/>
//    sci_phys,

//    /// <remarks/>
//    sci_politics,

//    /// <remarks/>
//    sci_religion,

//    /// <remarks/>
//    sci_tech,

//    /// <remarks/>
//    science,

//    /// <remarks/>
//    sf,

//    /// <remarks/>
//    sf_action,

//    /// <remarks/>
//    sf_cyberpunk,

//    /// <remarks/>
//    sf_detective,

//    /// <remarks/>
//    sf_fantasy,

//    /// <remarks/>
//    sf_heroic,

//    /// <remarks/>
//    sf_history,

//    /// <remarks/>
//    sf_horror,

//    /// <remarks/>
//    sf_humor,

//    /// <remarks/>
//    sf_social,

//    /// <remarks/>
//    sf_space,

//    /// <remarks/>
//    short_story,

//    /// <remarks/>
//    sketch,

//    /// <remarks/>
//    small_business,

//    /// <remarks/>
//    sociology_book,

//    /// <remarks/>
//    stock,

//    /// <remarks/>
//    thriller,

//    /// <remarks/>
//    upbringing_book,

//    /// <remarks/>
//    vampire_book,

//    /// <remarks/>
//    visual_arts,

//    /// <remarks/>
//    unrecognised,
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class titleinfoTypeAuthor : authorType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class FictionBookDescription {
    
    private titleinfoType titleinfoField;
    
    private titleinfoType srctitleinfoField;
    
    private FictionBookDescriptionDocumentinfo documentinfoField;
    
    private FictionBookDescriptionPublishinfo publishinfoField;
    
    private FictionBookDescriptionCustominfo[] custominfoField;
    
    private shareInstructionType[] outputField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("title-info")]
    public titleinfoType titleinfo {
        get {
            return this.titleinfoField;
        }
        set {
            this.titleinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("src-title-info")]
    public titleinfoType srctitleinfo {
        get {
            return this.srctitleinfoField;
        }
        set {
            this.srctitleinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("document-info")]
    public FictionBookDescriptionDocumentinfo documentinfo {
        get {
            return this.documentinfoField;
        }
        set {
            this.documentinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("publish-info")]
    public FictionBookDescriptionPublishinfo publishinfo {
        get {
            return this.publishinfoField;
        }
        set {
            this.publishinfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("custom-info")]
    public FictionBookDescriptionCustominfo[] custominfo {
        get {
            return this.custominfoField;
        }
        set {
            this.custominfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("output")]
    public shareInstructionType[] output {
        get {
            return this.outputField;
        }
        set {
            this.outputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class FictionBookDescriptionDocumentinfo {
    
    private authorType[] authorField;
    
    private textFieldType programusedField;
    
    private dateType dateField;
    
    private string[] srcurlField;
    
    private textFieldType srcocrField;
    
    private string idField;
    
    private float versionField;
    
    private annotationType historyField;
    
    private authorType[] publisherField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("author")]
    public authorType[] author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("program-used")]
    public textFieldType programused {
        get {
            return this.programusedField;
        }
        set {
            this.programusedField = value;
        }
    }
    
    /// <remarks/>
    public dateType date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("src-url")]
    public string[] srcurl {
        get {
            return this.srcurlField;
        }
        set {
            this.srcurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("src-ocr")]
    public textFieldType srcocr {
        get {
            return this.srcocrField;
        }
        set {
            this.srcocrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public float version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public annotationType history {
        get {
            return this.historyField;
        }
        set {
            this.historyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("publisher")]
    public authorType[] publisher {
        get {
            return this.publisherField;
        }
        set {
            this.publisherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class FictionBookDescriptionPublishinfo {
    
    private textFieldType booknameField;
    
    private textFieldType publisherField;
    
    private textFieldType cityField;
    
    private string yearField;
    
    private textFieldType isbnField;
    
    private sequenceType[] sequenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("book-name")]
    public textFieldType bookname {
        get {
            return this.booknameField;
        }
        set {
            this.booknameField = value;
        }
    }
    
    /// <remarks/>
    public textFieldType publisher {
        get {
            return this.publisherField;
        }
        set {
            this.publisherField = value;
        }
    }
    
    /// <remarks/>
    public textFieldType city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public textFieldType isbn {
        get {
            return this.isbnField;
        }
        set {
            this.isbnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sequence")]
    public sequenceType[] sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class FictionBookDescriptionCustominfo : textFieldType {
    
    private string infotypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("info-type")]
    public string infotype {
        get {
            return this.infotypeField;
        }
        set {
            this.infotypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
public partial class FictionBookBinary {
    
    private string contenttypeField;
    
    private string idField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("content-type")]
    public string contenttype {
        get {
            return this.contenttypeField;
        }
        set {
            this.contenttypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
